### ISSUE TITLE
Add an option to the GUI that allows the GUI to stay open after the task has been finished.

### ISSUE THREAD

**Issue by jonelo** [jonelo/HashGarten#3]
spin-off from issue#2

> After the popup window "HashGarten task has been finished" appears (and the main window vanishes) and I click OK, HashGarten terminates (exit status 0).

this is expected behavior, and makes sense if integrated in the file browser, but it should be controlled by the user, because it could be desired to continue with the next task if run in standalone mode. So feature request is:

Add an option to the GUI that allows the GUI to stay open after the task has been finished.

**Comment by mjk-gh** [comment]
Thanks for the explanation, and yes, I would support that option (because standalone is my only use case so far :-).

**Comment by jonelo** [comment]
I have just released HashGarten 0.15.0.
See also https://github.com/jonelo/HashGarten/releases/tag/v0.15.0

It addresses the issue described in this report.

**Comment by jonelo** [comment]
The new option can be fount at the tab called "Frontend".

![grafik](https://github.com/jonelo/HashGarten/assets/10409423/44e20793-46cd-44fc-8beb-e0c4d759d9a2)
