### ISSUE TITLE
bug: option traversing a directory

### ISSUE THREAD

**Issue by jsvt-AG** [jonelo/HashGarten#8]
First of all: thanks for the nice tool!

Testing the tool I noticed a bug, which I would like to report:
As soon as ‘Go down max. X level(s) when traversing a directory’ is activated, the setting for new calculations can only be changed by 
a) manually overwriting the value X in the option or
b) by deleting the ‘HashGarten.properties’ file
Even if the option is deactivated, the previously specified level depth is used for new calculations.

Expected behaviour: As soon as the option is deactivated, no level restrictions are applied to the (new) calculation.

OS: I'm using Windows 11

**Comment by jonelo** [comment]
good catch. Yes, it is a bug. I am going to fix it on the weekend.

**Comment by jsvt-AG** [comment]
Great, thanks a lot!

**Comment by jonelo** [comment]
It is fixed, a new installer has been made as well, see also 
https://github.com/jonelo/jacksum-for-windows/releases/tag/v2.9.0
